[package]
name = "comraksyntect"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "comraksyntect"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.22.0-rc.0"
lazy_static = "1.0"
comrak = "0.9.0"
syntect = "4.5.0"
